### ISSUE TITLE
Add phpcs.xml

### ISSUE THREAD

**Issue by stereomon** [spryker-sdk/spryk-src#3]
https://github.com/spryker-sdk/spryk-src/blob/feature/compiler/composer.json#L66-L67
Can we please move this into phpcs.xml as per new guidelines?

**Comment by dereuromark** [comment]
Example for other libraries can be found e.g. here
https://github.com/spryker-sdk/integrator/pull/22/files#diff-daa856500eea114bbf034fd35b7600050d965e5d19bb0700885c075747848fd8

**Comment by dereuromark** [comment]
This is still open it seems

**Comment by dereuromark** [comment]
https://github.com/spryker/suite-nonsplit/blob/master/phpcs.xml#L10
Please also add this
